export const sampleData: UserData[] = [
  {
    id: 1,
    name: "Joseph",
    address: "972 Onion St",
    status: "Resident",
    date: new Date("2025-02-21"),
  },
  {
    id: 2,
    name: "Madelyn",
    address: "803 Mushroom St",
    status: "Non-Resident",
    date: new Date("2024-04-02"),
  },
  {
    id: 3,
    name: "Madelyn",
    address: "427 Jalapeño St",
    status: "Visitor",
    date: new Date("2025-03-26"),
  },
  {
    id: 4,
    name: "Ethan",
    address: "204 Oak St",
    status: "Visitor",
    date: new Date("2024-03-31"),
  },
  {
    id: 5,
    name: "Jack",
    address: "279 Scorpion Pepper St",
    status: "Visitor",
    date: new Date("2024-09-12"),
  },
  {
    id: 6,
    name: "Aria",
    address: "381 Orange St",
    status: "Visitor",
    date: new Date("2024-09-09"),
  },
  {
    id: 7,
    name: "Emma",
    address: "910 Piri Piri St",
    status: "Visitor",
    date: new Date("2024-05-27"),
  },
  {
    id: 8,
    name: "Noah",
    address: "867 Watermelon St",
    status: "Visitor",
    date: new Date("2024-11-21"),
  },
  {
    id: 9,
    name: "Mason",
    address: "787 Thai Chili St",
    status: "Resident",
    date: new Date("2024-07-31"),
  },
  {
    id: 10,
    name: "Noah",
    address: "600 Sriracha St",
    status: "Visitor",
    date: new Date("2024-09-06"),
  },
  {
    id: 11,
    name: "Logan",
    address: "65 Pear St",
    status: "Resident",
    date: new Date("2024-08-03"),
  },
  {
    id: 12,
    name: "Carter",
    address: "999 Salsa St",
    status: "Resident",
    date: new Date("2025-03-18"),
  },
  {
    id: 13,
    name: "Sophie",
    address: "92 Bell Pepper St",
    status: "Resident",
    date: new Date("2024-06-25"),
  },
  {
    id: 14,
    name: "Luke",
    address: "30 Habanero Pepper St",
    status: "Resident",
    date: new Date("2024-09-07"),
  },
  {
    id: 15,
    name: "Ava",
    address: "480 Maple St",
    status: "Visitor",
    date: new Date("2024-11-25"),
  },
  {
    id: 16,
    name: "Isaac",
    address: "223 Maple St",
    status: "Resident",
    date: new Date("2024-11-21"),
  },
  {
    id: 17,
    name: "Sarah",
    address: "801 Cherry St",
    status: "Visitor",
    date: new Date("2024-08-25"),
  },
  {
    id: 18,
    name: "Ava",
    address: "983 Pear St",
    status: "Resident",
    date: new Date("2024-12-30"),
  },
  {
    id: 19,
    name: "Logan",
    address: "824 Grape St",
    status: "Non-Resident",
    date: new Date("2024-05-23"),
  },
  {
    id: 20,
    name: "Ethan",
    address: "937 Anaheim St",
    status: "Visitor",
    date: new Date("2024-04-20"),
  },
  {
    id: 21,
    name: "Michael",
    address: "201 Anaheim St",
    status: "Resident",
    date: new Date("2024-12-26"),
  },
  {
    id: 22,
    name: "Victoria",
    address: "223 Dragon's Breath St",
    status: "Non-Resident",
    date: new Date("2024-10-17"),
  },
  {
    id: 23,
    name: "Daniel",
    address: "413 Naga Viper St",
    status: "Resident",
    date: new Date("2025-01-30"),
  },
  {
    id: 24,
    name: "Liam",
    address: "375 Paprika St",
    status: "Resident",
    date: new Date("2024-08-30"),
  },
  {
    id: 25,
    name: "Sarah",
    address: "929 Carolina Reaper St",
    status: "Non-Resident",
    date: new Date("2024-04-01"),
  },
  {
    id: 26,
    name: "Logan",
    address: "219 Main St",
    status: "Visitor",
    date: new Date("2024-04-28"),
  },
  {
    id: 27,
    name: "Harper",
    address: "432 Scorpion Pepper St",
    status: "Visitor",
    date: new Date("2025-01-26"),
  },
  {
    id: 28,
    name: "Sebastian",
    address: "857 Potato St",
    status: "Visitor",
    date: new Date("2024-10-08"),
  },
  {
    id: 29,
    name: "Ella",
    address: "984 Garlic St",
    status: "Visitor",
    date: new Date("2024-09-17"),
  },
  {
    id: 30,
    name: "Jack",
    address: "918 Grape St",
    status: "Non-Resident",
    date: new Date("2024-11-11"),
  },
  {
    id: 31,
    name: "Charlotte",
    address: "443 Jalapeno St",
    status: "Visitor",
    date: new Date("2024-06-04"),
  },
  {
    id: 32,
    name: "Ethan",
    address: "987 Cayenne St",
    status: "Non-Resident",
    date: new Date("2024-10-18"),
  },
  {
    id: 33,
    name: "Michael",
    address: "1 Cayenne St",
    status: "Visitor",
    date: new Date("2024-11-07"),
  },
  {
    id: 34,
    name: "Jessica",
    address: "291 Jalapeno St",
    status: "Resident",
    date: new Date("2024-12-28"),
  },
  {
    id: 35,
    name: "Sarah",
    address: "42 Banana St",
    status: "Resident",
    date: new Date("2025-01-29"),
  },
  {
    id: 36,
    name: "Abigail",
    address: "546 Salsa St",
    status: "Resident",
    date: new Date("2024-06-05"),
  },
  {
    id: 37,
    name: "Olivia",
    address: "946 Watermelon St",
    status: "Non-Resident",
    date: new Date("2025-03-26"),
  },
  {
    id: 38,
    name: "Benjamin",
    address: "531 Piri Piri St",
    status: "Visitor",
    date: new Date("2024-07-27"),
  },
  {
    id: 39,
    name: "Jack",
    address: "908 Banana St",
    status: "Visitor",
    date: new Date("2024-07-22"),
  },
  {
    id: 40,
    name: "Joseph",
    address: "275 Serrano St",
    status: "Non-Resident",
    date: new Date("2024-05-29"),
  },
  {
    id: 41,
    name: "Ava",
    address: "138 Sriracha St",
    status: "Resident",
    date: new Date("2024-10-27"),
  },
  {
    id: 42,
    name: "William",
    address: "848 Apple St",
    status: "Resident",
    date: new Date("2024-12-02"),
  },
  {
    id: 43,
    name: "Noah",
    address: "671 Pear St",
    status: "Visitor",
    date: new Date("2024-09-22"),
  },
  {
    id: 44,
    name: "Sarah",
    address: "385 Cayenne St",
    status: "Non-Resident",
    date: new Date("2024-04-04"),
  },
  {
    id: 45,
    name: "Noah",
    address: "614 Thai Chili St",
    status: "Visitor",
    date: new Date("2024-05-27"),
  },
  {
    id: 46,
    name: "David",
    address: "65 Infinity Chili St",
    status: "Visitor",
    date: new Date("2025-03-10"),
  },
  {
    id: 47,
    name: "Abigail",
    address: "21 Jalapeño St",
    status: "Visitor",
    date: new Date("2024-09-28"),
  },
  {
    id: 48,
    name: "Emma",
    address: "687 Infinity Chili St",
    status: "Resident",
    date: new Date("2025-02-15"),
  },
  {
    id: 49,
    name: "Ava",
    address: "904 Pear St",
    status: "Non-Resident",
    date: new Date("2024-08-15"),
  },
  {
    id: 50,
    name: "Joseph",
    address: "610 Ghost Pepper St",
    status: "Non-Resident",
    date: new Date("2025-03-03"),
  },
  {
    id: 51,
    name: "Madelyn",
    address: "146 Onion St",
    status: "Non-Resident",
    date: new Date("2025-01-01"),
  },
  {
    id: 52,
    name: "Amanda",
    address: "922 Tabasco St",
    status: "Visitor",
    date: new Date("2024-12-23"),
  },
  {
    id: 53,
    name: "Chloe",
    address: "333 Paprika St",
    status: "Visitor",
    date: new Date("2024-05-20"),
  },
  {
    id: 54,
    name: "Chloe",
    address: "755 Sriracha St",
    status: "Resident",
    date: new Date("2024-06-14"),
  },
  {
    id: 55,
    name: "Elijah",
    address: "915 Salsa St",
    status: "Non-Resident",
    date: new Date("2024-05-13"),
  },
  {
    id: 56,
    name: "Jack",
    address: "661 Carolina Reaper St",
    status: "Non-Resident",
    date: new Date("2024-11-23"),
  },
  {
    id: 57,
    name: "Isaac",
    address: "218 Birch St",
    status: "Non-Resident",
    date: new Date("2024-11-13"),
  },
  {
    id: 58,
    name: "Elijah",
    address: "711 Serrano St",
    status: "Non-Resident",
    date: new Date("2024-04-23"),
  },
  {
    id: 59,
    name: "Sophie",
    address: "318 Elm St",
    status: "Visitor",
    date: new Date("2024-12-06"),
  },
  {
    id: 60,
    name: "Lily",
    address: "678 Scorpion Pepper St",
    status: "Visitor",
    date: new Date("2025-03-20"),
  },
  {
    id: 61,
    name: "Aubrey",
    address: "725 Pear St",
    status: "Visitor",
    date: new Date("2024-10-25"),
  },
  {
    id: 62,
    name: "Alexander",
    address: "516 Pineapple St",
    status: "Resident",
    date: new Date("2024-08-30"),
  },
  {
    id: 63,
    name: "Carter",
    address: "725 Lemon St",
    status: "Visitor",
    date: new Date("2025-02-20"),
  },
  {
    id: 64,
    name: "Abigail",
    address: "16 Anaheim St",
    status: "Non-Resident",
    date: new Date("2024-11-23"),
  },
  {
    id: 65,
    name: "James",
    address: "557 Cucumber St",
    status: "Visitor",
    date: new Date("2025-01-05"),
  },
  {
    id: 66,
    name: "Mason",
    address: "712 Tabasco St",
    status: "Resident",
    date: new Date("2024-07-27"),
  },
  {
    id: 67,
    name: "Sebastian",
    address: "647 Thai Chili St",
    status: "Non-Resident",
    date: new Date("2024-11-19"),
  },
  {
    id: 68,
    name: "William",
    address: "959 Cucumber St",
    status: "Non-Resident",
    date: new Date("2025-01-24"),
  },
  {
    id: 69,
    name: "Sophia",
    address: "834 Tomato St",
    status: "Non-Resident",
    date: new Date("2024-10-04"),
  },
  {
    id: 70,
    name: "Ella",
    address: "268 Orange St",
    status: "Resident",
    date: new Date("2024-11-13"),
  },
  {
    id: 71,
    name: "Avery",
    address: "992 Onion St",
    status: "Visitor",
    date: new Date("2024-05-03"),
  },
  {
    id: 72,
    name: "Jackson",
    address: "206 Chili St",
    status: "Visitor",
    date: new Date("2024-09-26"),
  },
  {
    id: 73,
    name: "Noah",
    address: "604 Banana St",
    status: "Resident",
    date: new Date("2024-09-04"),
  },
  {
    id: 74,
    name: "Carter",
    address: "917 Jalapeno St",
    status: "Non-Resident",
    date: new Date("2024-04-08"),
  },
  {
    id: 75,
    name: "Olivia",
    address: "844 Lemon St",
    status: "Non-Resident",
    date: new Date("2024-11-01"),
  },
  {
    id: 76,
    name: "Harper",
    address: "895 Mushroom St",
    status: "Visitor",
    date: new Date("2024-12-06"),
  },
  {
    id: 77,
    name: "Matthew",
    address: "918 Apple St",
    status: "Non-Resident",
    date: new Date("2024-06-02"),
  },
  {
    id: 78,
    name: "Ella",
    address: "474 Sriracha St",
    status: "Non-Resident",
    date: new Date("2024-04-09"),
  },
  {
    id: 79,
    name: "Scarlett",
    address: "43 Cedar St",
    status: "Non-Resident",
    date: new Date("2024-04-01"),
  },
  {
    id: 80,
    name: "Benjamin",
    address: "721 Pine St",
    status: "Resident",
    date: new Date("2024-05-20"),
  },
  {
    id: 81,
    name: "Hannah",
    address: "963 Main St",
    status: "Resident",
    date: new Date("2025-03-15"),
  },
  {
    id: 82,
    name: "Olivia",
    address: "194 Cucumber St",
    status: "Non-Resident",
    date: new Date("2024-09-19"),
  },
  {
    id: 83,
    name: "David",
    address: "728 Thai Chili St",
    status: "Non-Resident",
    date: new Date("2024-07-04"),
  },
  {
    id: 84,
    name: "Chloe",
    address: "391 Paprika St",
    status: "Non-Resident",
    date: new Date("2024-04-05"),
  },
  {
    id: 85,
    name: "Madelyn",
    address: "295 Potato St",
    status: "Non-Resident",
    date: new Date("2025-03-09"),
  },
  {
    id: 86,
    name: "Victoria",
    address: "368 Elm St",
    status: "Visitor",
    date: new Date("2024-06-07"),
  },
  {
    id: 87,
    name: "Emma",
    address: "684 Pear St",
    status: "Non-Resident",
    date: new Date("2024-07-26"),
  },
  {
    id: 88,
    name: "Daniel",
    address: "976 Habanero St",
    status: "Resident",
    date: new Date("2024-10-22"),
  },
  {
    id: 89,
    name: "James",
    address: "274 Tomato St",
    status: "Non-Resident",
    date: new Date("2024-09-09"),
  },
  {
    id: 90,
    name: "Jack",
    address: "54 Cayenne St",
    status: "Resident",
    date: new Date("2024-11-18"),
  },
  {
    id: 91,
    name: "Lily",
    address: "402 Chili St",
    status: "Visitor",
    date: new Date("2024-04-20"),
  },
  {
    id: 92,
    name: "Joseph",
    address: "291 Tomato St",
    status: "Visitor",
    date: new Date("2025-03-26"),
  },
  {
    id: 93,
    name: "William",
    address: "151 Piri Piri St",
    status: "Visitor",
    date: new Date("2024-07-26"),
  },
  {
    id: 94,
    name: "Ava",
    address: "586 Lemon St",
    status: "Resident",
    date: new Date("2024-08-17"),
  },
  {
    id: 95,
    name: "Sarah",
    address: "850 Jalapeno St",
    status: "Non-Resident",
    date: new Date("2024-10-25"),
  },
  {
    id: 96,
    name: "Aria",
    address: "4 Elm St",
    status: "Non-Resident",
    date: new Date("2024-10-06"),
  },
  {
    id: 97,
    name: "Joseph",
    address: "412 Poblano St",
    status: "Visitor",
    date: new Date("2024-04-17"),
  },
  {
    id: 98,
    name: "Liam",
    address: "929 Oak St",
    status: "Resident",
    date: new Date("2024-09-12"),
  },
  {
    id: 99,
    name: "Logan",
    address: "163 Infinity Chili St",
    status: "Visitor",
    date: new Date("2024-11-09"),
  },
  {
    id: 100,
    name: "Mason",
    address: "323 Serrano St",
    status: "Non-Resident",
    date: new Date("2024-12-15"),
  },
  {
    id: 101,
    name: "Daniel",
    address: "164 Main St",
    status: "Visitor",
    date: new Date("2024-03-31"),
  },
  {
    id: 102,
    name: "Liam",
    address: "907 Ghost Pepper St",
    status: "Resident",
    date: new Date("2024-07-27"),
  },
  {
    id: 103,
    name: "Ethan",
    address: "630 Watermelon St",
    status: "Non-Resident",
    date: new Date("2024-10-31"),
  },
  {
    id: 104,
    name: "Scarlett",
    address: "499 Cedar St",
    status: "Non-Resident",
    date: new Date("2024-12-20"),
  },
  {
    id: 105,
    name: "Emma",
    address: "404 Plum St",
    status: "Visitor",
    date: new Date("2025-02-11"),
  },
  {
    id: 106,
    name: "Matthew",
    address: "577 Orange St",
    status: "Non-Resident",
    date: new Date("2024-11-08"),
  },
  {
    id: 107,
    name: "William",
    address: "377 Oak St",
    status: "Visitor",
    date: new Date("2024-09-20"),
  },
  {
    id: 108,
    name: "Owen",
    address: "198 Naga Viper St",
    status: "Visitor",
    date: new Date("2025-03-22"),
  },
  {
    id: 109,
    name: "Liam",
    address: "334 Salsa St",
    status: "Visitor",
    date: new Date("2024-08-26"),
  },
  {
    id: 110,
    name: "Avery",
    address: "89 Onion St",
    status: "Resident",
    date: new Date("2024-10-27"),
  },
  {
    id: 111,
    name: "Andrew",
    address: "64 Onion St",
    status: "Resident",
    date: new Date("2024-04-11"),
  },
  {
    id: 112,
    name: "Daniel",
    address: "705 Jalapeño St",
    status: "Resident",
    date: new Date("2025-03-18"),
  },
  {
    id: 113,
    name: "Nicholas",
    address: "858 Lemon St",
    status: "Non-Resident",
    date: new Date("2024-12-16"),
  },
  {
    id: 114,
    name: "William",
    address: "871 Orange St",
    status: "Visitor",
    date: new Date("2024-05-24"),
  },
  {
    id: 115,
    name: "Madelyn",
    address: "577 Bell Pepper St",
    status: "Resident",
    date: new Date("2024-12-22"),
  },
  {
    id: 116,
    name: "Aubrey",
    address: "581 Mushroom St",
    status: "Non-Resident",
    date: new Date("2024-07-16"),
  },
  {
    id: 117,
    name: "Emma",
    address: "741 Chili St",
    status: "Resident",
    date: new Date("2024-08-29"),
  },
  {
    id: 118,
    name: "Logan",
    address: "342 Infinity Chili St",
    status: "Resident",
    date: new Date("2024-04-23"),
  },
  {
    id: 119,
    name: "Daniel",
    address: "484 Habanero Pepper St",
    status: "Non-Resident",
    date: new Date("2024-09-03"),
  },
  {
    id: 120,
    name: "Charlotte",
    address: "671 Apple St",
    status: "Visitor",
    date: new Date("2024-06-09"),
  },
  {
    id: 121,
    name: "Andrew",
    address: "52 Ghost Pepper St",
    status: "Non-Resident",
    date: new Date("2024-04-17"),
  },
  {
    id: 122,
    name: "Chloe",
    address: "666 Elm St",
    status: "Non-Resident",
    date: new Date("2024-04-16"),
  },
  {
    id: 123,
    name: "Lily",
    address: "601 Birch St",
    status: "Non-Resident",
    date: new Date("2024-09-09"),
  },
  {
    id: 124,
    name: "Luke",
    address: "454 Paprika St",
    status: "Resident",
    date: new Date("2024-04-16"),
  },
  {
    id: 125,
    name: "Avery",
    address: "879 Birch St",
    status: "Non-Resident",
    date: new Date("2024-10-23"),
  },
  {
    id: 126,
    name: "Elijah",
    address: "441 Poblano St",
    status: "Non-Resident",
    date: new Date("2025-03-05"),
  },
  {
    id: 127,
    name: "David",
    address: "692 Orange St",
    status: "Visitor",
    date: new Date("2024-12-30"),
  },
  {
    id: 128,
    name: "Andrew",
    address: "698 Infinity Chili St",
    status: "Resident",
    date: new Date("2024-08-07"),
  },
  {
    id: 129,
    name: "Daniel",
    address: "497 Pineapple St",
    status: "Resident",
    date: new Date("2024-06-13"),
  },
  {
    id: 130,
    name: "Elijah",
    address: "814 Poblano St",
    status: "Resident",
    date: new Date("2024-07-05"),
  },
  {
    id: 131,
    name: "Emma",
    address: "753 Tomato St",
    status: "Resident",
    date: new Date("2025-03-23"),
  },
  {
    id: 132,
    name: "Lily",
    address: "297 Onion St",
    status: "Resident",
    date: new Date("2024-10-24"),
  },
  {
    id: 133,
    name: "Chloe",
    address: "734 Paprika St",
    status: "Non-Resident",
    date: new Date("2024-11-23"),
  },
  {
    id: 134,
    name: "Madelyn",
    address: "67 Lemon St",
    status: "Visitor",
    date: new Date("2025-01-07"),
  },
  {
    id: 135,
    name: "Harper",
    address: "829 Apple St",
    status: "Resident",
    date: new Date("2024-09-19"),
  },
  {
    id: 136,
    name: "Harper",
    address: "551 Sriracha St",
    status: "Resident",
    date: new Date("2024-12-02"),
  },
  {
    id: 137,
    name: "Madelyn",
    address: "748 Onion St",
    status: "Visitor",
    date: new Date("2025-03-16"),
  },
  {
    id: 138,
    name: "Luke",
    address: "181 Lemon St",
    status: "Non-Resident",
    date: new Date("2024-11-12"),
  },
  {
    id: 139,
    name: "Daniel",
    address: "342 Oak St",
    status: "Non-Resident",
    date: new Date("2025-02-18"),
  },
  {
    id: 140,
    name: "Victoria",
    address: "124 Salsa St",
    status: "Resident",
    date: new Date("2025-01-11"),
  },
  {
    id: 141,
    name: "Daniel",
    address: "570 Cucumber St",
    status: "Visitor",
    date: new Date("2024-06-20"),
  },
  {
    id: 142,
    name: "Carter",
    address: "319 Grape St",
    status: "Visitor",
    date: new Date("2024-05-10"),
  },
  {
    id: 143,
    name: "Matthew",
    address: "825 Scorpion Pepper St",
    status: "Visitor",
    date: new Date("2024-06-25"),
  },
  {
    id: 144,
    name: "Benjamin",
    address: "380 Lemon St",
    status: "Resident",
    date: new Date("2024-09-03"),
  },
  {
    id: 145,
    name: "Daniel",
    address: "704 Banana St",
    status: "Visitor",
    date: new Date("2024-09-12"),
  },
  {
    id: 146,
    name: "Emily",
    address: "810 Naga Viper St",
    status: "Non-Resident",
    date: new Date("2024-08-06"),
  },
  {
    id: 147,
    name: "Matthew",
    address: "530 Scorpion Pepper St",
    status: "Non-Resident",
    date: new Date("2025-03-20"),
  },
  {
    id: 148,
    name: "Daniel",
    address: "6 Cayenne Pepper St",
    status: "Non-Resident",
    date: new Date("2025-01-08"),
  },
  {
    id: 149,
    name: "Charlotte",
    address: "919 Watermelon St",
    status: "Non-Resident",
    date: new Date("2024-12-14"),
  },
  {
    id: 150,
    name: "Nicholas",
    address: "402 Naga Viper St",
    status: "Visitor",
    date: new Date("2024-06-01"),
  },
];

export interface UserData {
  id: number;
  name: string;
  address: string;
  status: string;
  date: Date;
}
